apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: load-test-runner
spec:
  serviceAccountName: amerah-docker-hub
  taskRef:
    name: load-test
  params:
  - name: IMAGE
    value: "amerahsultan1/load-test"
  resources:
    inputs:
    - name: level3-project
      resourceRef:
        name: load-test-resource

