apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-prod-task
  namespace: prod
spec:
  resources:
    inputs:
    - name: level3-project
      type: git
  params:
  - name: pathToYamlFile
    description: The path to the yaml file to deploy within the git source
  steps:
  - name: run-kubectl
    command: ["kubectl"]
    args:
      - "apply"
      - "-f"
      - "/workspace/$(inputs.params.pathToYamlFile)"
