apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: e2e-js-test-pipelinerun 
spec:
  pipelineRef:
    name: e2e-js-test-pipeline
  resources:
    - name: level3-project
      resourceRef:
        name: e2e-js-test-resource
  params:
    - name: IMAGE
      value: "amerahsultan1/e2e-js-test"
    - name: CONTEXT
      value: "/workspace/level3-project/e2e-js-test"
    - name: DOCKERFILE
      value: "/workspace/level3-project/e2e-js-test/Dockerfile"
  serviceAccountName: amerah-docker-hub
