apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: load-test-pipelinerun 
spec:
  pipelineRef:
    name: load-test-pipeline
  resources:
    - name: level3-project
      resourceRef:
        name: load-test-resource
  params:
    - name: pathToYamlFile
      value: "level3-project/deployment/load-test/loadtest-dep.yaml"
    - name: imageUrl
      value: "amerahsultan1/load-test"
    - name: imageTag
      value: "latest"
    - name: IMAGE
      value: "amerahsultan1/load-test"
      
  serviceAccountName: amerah-docker-hub
