apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: orders-runner
spec:
  serviceAccountName: amerah-docker-hub
  taskRef:
    name: orders
  params:
  - name: IMAGE
    value: "amerahsultan1/orders"
  resources:
    inputs:
    - name: level3-project
      resourceRef:
        name: orders-resource
