apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: queue-master-runner
spec:
  serviceAccountName: amerah-docker-hub
  taskRef:
    name: queue-master 
  params:
  - name: IMAGE
    value: "amerahsultan1/queue-master"
  resources:
    inputs:
    - name: level3-project
      resourceRef:
        name: queue-master-resource

