apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: role-binding-socks-shop
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: role-socks-shop
subjects:
  - kind: ServiceAccount
    name: amerah-docker-hub
    namespace: test
