apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: front-end-runner
spec:
  serviceAccountName: amerah-docker-hub
  taskRef:
    name: front-end
  params:
  - name: IMAGE
    value: "amerahsultan1/front-end"
  resources:
    inputs:
    - name: level3-project
      resourceRef:
        name: front-end-resource
