apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: rabbitmq-pipeline
spec:
  resources:
    - name: level3-project
      type: git
  params:
    - name: pathToYamlFile
      type: string
      default: "level3-project/deployment/rabbitmq/rabbitmq-dep.yaml"
    - name: imageUrl
      type: string
      default: "rabbitmq"
    - name: imageTag
      type: string
      default: "3.6.8-management"
    - name: namespace
      type: string
      default: "test"
    - name: service-name
      type: string
      default: "rabbitmq"
  tasks:
  - name: run-deploy-image
    taskRef:
      name: deploy-task
    params:
      - name: pathToYamlFile
        value:  "$(params.pathToYamlFile)"
      - name: imageUrl
        value: "$(params.imageUrl)"
      - name: imageTag
        value: "$(params.imageTag)"
    resources:
      inputs:
        - name: level3-project
          resource: level3-project
  - name: wait-pods-status
    taskRef:
      name: wait-pods-status
    runAfter:
      - run-deploy-image
    params:
      - name: namespace
        value: "$(params.namespace)"
      - name: serivce-name
        value: "$(params.service-name)"
    resources:
      inputs:
        - name: level3-project
          resource: level3-project
  - name: run-test
    taskRef:
      name: run-e2e-test-task
    runAfter:
      - wait-pods-status
    resources:
      inputs:
        - name: level3-project
          resource: level3-project
  - name: deploy-prod
    taskRef:
      name: deploy-prod-task
    runAfter:
      - run-test
    resources:
      inputs:
        - name: level3-project
          resource: level3-project
