apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: shipping-pipeline
spec:
  resources:
    - name: level3-project
      type: git
  params:
    - name: CONTEXT
      type: string
      default: "/workspace/level3-project/shipping"
    - name: IMAGE
      type: string
      default: "amerahsultan1/shipping"
    - name: DOCKERFILE
      type: string
      default: "/workspace/level3-project/shipping/Dockerfile"
    - name: pathToYamlFile
      type: string
      default: "level3-project/deployment/shipping/shipping-dep.yaml"
    - name: imageUrl
      type: string
      default: "amerahsultan1/shipping"
    - name: imageTag
      type: string
      default: "latest"
    - name: namespace
      type: string
      default: "test"
    - name: service-name
      type: string
      default: "shipping"
  tasks:
  - name: build-push-image
    taskRef:
      name: build-push-task
    params:
      - name: CONTEXT
        value: "$(params.CONTEXT)"
      - name: IMAGE
        value: "$(params.IMAGE)"
      - name: DOCKERFILE
        value: "$(params.DOCKERFILE)"
    resources:
      inputs:
        - name: level3-project
          resource: level3-project
  - name: microservice-deploy
    taskRef:
      name: deploy-task
    runAfter:
      - build-push-image
    params:
      - name: pathToYamlFile
        value:  "$(params.pathToYamlFile)"
      - name: imageUrl
        value: "$(params.imageUrl)"
      - name: imageTag
        value: "$(params.imageTag)"
    resources:
      inputs:
        - name: level3-project
          resource: level3-project
  - name: wait-pods-status
    taskRef:
      name: wait-pods-status
    runAfter:
      - microservice-deploy
    params:
      - name: namespace
        value: "$(params.namespace)"
      - name: serivce-name
        value: "$(params.service-name)"
    resources:
      inputs:
        - name: level3-project
          resource: level3-project
  - name: run-test
    taskRef:
      name: run-e2e-test-task
    runAfter:
      - wait-pods-status
    resources:
      inputs:
        - name: level3-project
          resource: level3-project
  - name: deploy-prod
    taskRef:
      name: deploy-prod-task
    runAfter:
      - run-test
    resources:
      inputs:
        - name: level3-project
          resource: level3-project
