apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: user-pipelinerun 
spec:
  pipelineRef:
    name: user-pipeline
  resources:
    - name: level3-project
      resourceRef:
        name: user-resource
  params:
    - name: IMAGE-db
      value: "amerahsultan1/user-db"
    - name: IMAGE
      value: "amerahsultan1/user"
    - name: pathToYamlFile
      value: "level3-project/deployment/user/user-dep.yaml"
    - name: imageUrl
      value: "amerahsultan1/user"
    - name: imageTag
      value: "latest"
    - name: pathToYamlFile-db
      value: "level3-project/deployment/user/user-db-dep.yaml"
    - name: imageUrl-db
      value: "amerahsultan1/user-db"
    - name: imageTag-db
      value: "latest"
      
  serviceAccountName: amerah-docker-hub
