apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: e2e-js-test-pipelinerun 
spec:
  pipelineRef:
    name: e2e-js-test-pipeline
  resources:
    - name: level3-project
      resourceRef:
        name: e2e-js-test-resource
  params:
    - name: imageUrl
      value: "amerahsultan1/e2e-js-test"
    - name: imageTag
      value: "latest"
    - name: IMAGE
      value: "amerahsultan1/e2e-js-test"
      
  serviceAccountName: amerah-docker-hub
