apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: shipping-runner
spec:
  serviceAccountName: amerah-docker-hub
  taskRef:
    name: shipping
  params:
  - name: IMAGE
    value: "amerahsultan1/shipping"
  resources:
    inputs:
    - name: level3-project
      resourceRef:
        name: shipping-resource
