apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: user-runner
spec:
  serviceAccountName: amerah-docker-hub
  taskRef:
    name: user
  params:
  - name: IMAGE
    value: "amerahsultan1/users"
  resources:
    inputs:
    - name: level3-project
      resourceRef:
        name: level3-project
