apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: queue-master-pipelinerun 
spec:
  pipelineRef:
    name: queue-master-pipeline
  resources:
    - name: level3-project
      resourceRef:
        name: queue-master-resource
  params:
    - name: CONTEXT
      value: "/workspace/level3-project/queue-master"
    - name: DOCKERFILE
      value: "/workspace/level3-project/queue-master/Dockerfile"
    - name: pathToYamlFile
      value: "level3-project/deployment/queue-master/queue-master-dep.yaml"
    - name: imageUrl
      value: "amerahsultan1/queue-master"
    - name: imageTag
      value: "latest"
    - name: IMAGE
      value: "amerahsultan1/queue-master"
      
  serviceAccountName: amerah-docker-hub
